idf_component_register(SRCS "app_main.c"
                            "../core/camera_state.c"
                            "../core/camera_backend.c"
                            "../core/controller.c"
                            "../core/pairing.c"
                            "../core/ble_common.c"
                            "../adapters/dji/dji_ble.c"
                            "../adapters/dji/dji_data.c"
                            "../adapters/dji/dji_protocol_parser.c"
                            "../adapters/dji/dji_protocol_processor.c"
                            "../adapters/dji/dji_protocol_descriptors.c"
                            "../adapters/dji/dji_protocol_structures.c"
                            "../adapters/dji/dji_command.c"
                            "../adapters/dji/dji_connect.c"
                            "../adapters/dji/dji_status.c"
                            "../adapters/dji/dji_backend.c"
                            "../adapters/dji/dji_gps.c"
                            "../adapters/insta360/insta360.c"
                            "../adapters/insta360/insta360_backend.c"
                            "../adapters/insta360/insta360_gps.c"
                            "../services/gps.c"
                            "../services/gps_fusion.c"
                            "../services/gps_fusion_math.c"
                            "../services/osd.c"
                            "../services/fc_msp.c"
                            "../services/osd_config.c"
                            "../services/channel_map.c"
                            "../services/key.c"
                            "../services/light.c"
                            "../services/web_server.c"
                            "../shared/camera_enums.c"
                            "../shared/nvs_util.c"
                            "../shared/crc/custom_crc16.c"
                            "../shared/crc/custom_crc32.c"
                    PRIV_REQUIRES bt nvs_flash esp_driver_uart esp_driver_gpio led_strip msp esp_wifi esp_http_server esp_event esp_netif app_update cjson
                    EMBED_FILES "web/index.html"
                    INCLUDE_DIRS "." "../core" "../adapters/dji" "../adapters/insta360" "../services" "../shared" "../shared/crc")
